BEGIN {
  collecting_proto = 0;
  printf "// Prototypes generated by awk script\n"
}

{
  if (($0 ~ /^[a-zA-Z_].*\(.*$/) && 0 == collecting_proto) {
    printf "%s", $0;
    collecting_proto = 1;
  } else if ($0 ~ /^\{ *$/) {
    printf ";\n";
    collecting_proto = 0;
  } else if (1 == collecting_proto) {
    t = $0;
    sub(/^[ \t]*/, "", t);
    printf "%s", t;
  }
}
